#!/usr/bin/python3
#
## Copyright (C) 2016,Tianjin KYLIN Information Technology Co., Ltd.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
## Free Software Foundation, Inc.,
## 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

import gi
import sys
import ukui_menu.menueditor as menueditor
from gi.repository import Gio

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

def on_delete(widget, event):
    Gtk.main_quit()

def on_close_button_clicked(button):
    Gtk.main_quit()

settings = Gio.Settings.new("org.ukui.ukui-menu")
showCategoryMenu = settings.get_boolean("show-category-menu")
if showCategoryMenu == False:
    msg = _("\nCurrent menu mode is not category mode, please switch and try again!")
    md = Gtk.MessageDialog(None, 0, Gtk.MessageType.WARNING, Gtk.ButtonsType.OK, msg)
    md.run()
    md.destroy()
    exit()
app = menueditor.MenuEditMainWindow()
app.tree.get_object('mainwindow').connect("delete-event", on_delete)
app.tree.get_object('close_button').connect("clicked", on_close_button_clicked)
app.run()
Gtk.main()

