.\" Man page for ukui-menu
.TH UKUIMENU 1 "17 December 2019" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
ukui-menu \- The tool for the UKUI Desktop Environment
.SH "SYNOPSIS"
.B ukui-menu
.SH "DESCRIPTION"
The \fBukui-menu\fR program is a part of the ukui-menu, it provides users with graphical interface tools.
.PP
This manual page documents the \fBukui-menu\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/explorer-cs/ukui-start-menu/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
liuhao <liuhao@kylinos.cn> (2019)
.SH "SEE ALSO"
