/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.ukui.menu.xml -i dbus.h -a dbus-adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUS-ADAPTOR_H
#define DBUS-ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbus.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.ukui.menu
 */
class MenuAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ukui.menu")
    Q_CLASSINFO("D-Bus Introspection", ""
                "  <interface name=\"org.ukui.menu\">\n"
                "    <method name=\"GetSecurityConfigPath\">\n"
                "      <arg direction=\"out\" type=\"s\"/>\n"
                "    </method>\n"
                "    <method name=\"ReloadSecurityConfig\"/>\n"
                "    <method name=\"WinKeyResponse\"/>\n"
                "  </interface>\n"
                "")
public:
    MenuAdaptor(QObject *parent);
    virtual ~MenuAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetSecurityConfigPath();
    void ReloadSecurityConfig();
    void WinKeyResponse();
Q_SIGNALS: // SIGNALS
};

#endif
