.TH ukui\-menu 1 "" ""
.SH NAME
ukui-menu \- Advanced menu for the UKUI desktop environment's panel
.SH SYNOPSIS
.B ukui-menu \fR[option]
.SH DESCRIPTION
An advanced menu for UKUI. Supports filtering, favorites, autosession,
and many other features.

.SH OPTIONS
.TP
.B [\-\-]help\fR,\fB [\-]h\fR,\fB [\-]?
Display command line options.
.TP
.B [\-\-]clean\fR,\fB [\-\-]clear\fR,\fB [\-\-]reset
Restore the UKUI Menu settings to default by deleting the settings file (\fI~/.config/ukui-menu/\fR).
